#!/bin/sh -e
file="${@}"
if [[ $file == "Jobgroups/Tumbleweed_x86_64.yaml" ]]
then
  GROUPID=1
elif [[ $file == "Jobgroups/Leap_15.yaml" ]]
then
  GROUPID=50
else
  echo "Job group parameters not added."
  exit 1
fi
echo $GROUPID
