#!/bin/sh -e
file="${@}"

if [[ "$file" == "Jobgroups/Tumbleweed.yaml" ]]
then
  GROUPID=2
elif [[ "$file" = "Jobgroups/Leap_15.yaml" ]]
then
  GROUPID=50
else
  echo "Job group parameters not added in CI scripts/post_yaml"
  exit 1
fi

openqa-client --host http://falafel.suse.cz --apikey ${{ secrets.APIKEY }} --apisecret ${{ secrets.APISECRET }} job_templates_scheduling/$GROUPID post --form schema=Jobtemplates-01.yaml preview=1 template="$(cat $file)"
