#!/bin/sh -e
file="${@}"

if [[ $file=="Jobgroups/Tumbleweed.yaml" ]]; then
  $GROUPID=1
else [[ $file="Jobgroups/Leap_15.yaml" ]]
  $GROUPID=50
fi

openqa-client --host http://openqa.opensuse.org --apikey $APIKEY --apisecret $APISECRET job_templates_scheduling/$GROUPID post --form schema=Jobtemplates-01.yaml preview=1 template="$(cat $file)"
